main: me.knighthat.GUIKhoiDau.Main
name: GUIKhoiDau
author: KnightHat
version: 1.2
api-version: 1.13
soft-depend: [PlaceholderAPI, Vault]

commands:
  guikhoidau:
    permissions:
      - guikhoidau.admin
      - guikhoidau.momenu
      - guikhoidau.momenu.nguoikhac
    aliases:
      - guikd
      - gkd
  